### PR TITLE
Waitlist Frontend pt 2

### PR DESCRIPTION
**Pull request by gelilak**
added waitlist component to event registration page

### CODE REVIEW

**Comment by alexychen2002** [comment]
could you double check that handleRoleShiftSelection is working as intended? the event.target.value in that function should refer to the role shift's id in Strapi and should therefore print a number. i believe that it is not currently and is messing with the submit signup functionality.

**Comment by alexychen2002** [comment]
just 1 more small thing, the desktop view looks good, but could you also make sure that it is compatible with mobile view.

**Comment by gelilak** [comment]
Screenshot 2024-05-02 at 8 45 28 AM

**Comment by alexychen2002** [comment]
thank you! merged in recent waitlist commit

**Pull request closed without merging**
